spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/quotes-great-people
#    username: ${postgres.user.name:postgres}
#    password: ${postgres.user.name:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.PostgreSQL81Dialect
#        show_sql: true
#        format_sql: true
    hibernate:
#      ddl-auto: validate
      ddl-auto: create